name: Build and Test

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: python -m pip install build
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Build wheels
        run: python -m build .

      - uses: actions/upload-artifact@v3
        with:
          name: k3d_wheel
          path: ./dist/k3d*.whl
      - uses: actions/upload-artifact@v3
        with:
          name: k3d_sdist
          path: ./dist/k3d*.tar.gz
  test:
    name: Run pytest on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04 ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install
        run: |
          python -m pip install -e ".[dev,examples]"
          cd js
          npm install
          cd ..
          npm install
      - name: Run tests
        run: cd k3d && python -m pytest -k "not examples"
      - uses: actions/upload-artifact@v3
        with:
          name: comparison_results
          path: ./k3d/test/results/*

  examples:
    name: Run pytest on notebook examples
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install
        run: |
          python -m pip install -e ".[dev,examples]"
          cd js
          npm install
          cd ..
          npm install
      - name: Run tests
        run: cd k3d && python -m pytest -k "examples"

  try_binder:
    name: Build binder environment
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: repo2docker Action
      uses: jupyterhub/repo2docker-action@0.2
      with:
        NO_PUSH: 1
